security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
broker.store:
  node: ${zk.brk.store:/zkbrk_store}
broker.root:
  node: ${zk.brk.root:/platform}
zk:
  cluster: ${zk.cluster.url:}
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:zookeeper}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:zookeeper}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
metadata:
  imageUrl: ${IMAGE_URL:}

logging.level.org.trustedanalytics: INFO
