security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
broker.store:
  node: ${zk.brk.space:/zkbrk_space}
broker.root:
  node: ${zk.brk.root:/platform}
zk:
  cluster: ${zk.cluster.url:}
  brokerusername: cf
  brokeruserpass: cf1
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:zookeeper}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:zookeeper}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
kerberos:
  kdc: ${krb.kdc.host:}
  realm: ${krb.realm:}
metadata:
  imageUrl: ${IMAGE_URL:}