security:
  #password cf client will use when interacting with broker
  user.password: ${user.password}
broker.root:
  #path for provisiong znodes
  node: ${zk.brk.root:}
zk:
  #adress of zookeeper
  cluster: ${zk.cluster.url:}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/zookeeper/metadata}
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:zookeeper}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:zookeeper}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
metadata:
  #encoded image file viewed in marketplace
  imageUrl: ${IMAGE_URL:}
